// FF.Infrastructure/Persistence/Mongo/Repositories/NflScheduleRepository.cs
using FF.Application.Interfaces.Repositories;
using FF.Domain.Documents;
using FF.Domain.Services;
using MongoDB.Driver;

namespace FF.Infrastructure.Persistence.Mongo.Repositories;

public class NflScheduleRepository(MongoDbContext db) : INflScheduleRepository
{
    private readonly IMongoCollection<NflScheduleDocument> _collection =
        db.GetCollection<NflScheduleDocument>("nfl_schedule");

    public async Task UpsertBatchAsync(
        IReadOnlyList<NflScheduleDocument> games,
        CancellationToken ct = default)
    {
        if (games.Count == 0) return;

        var writes = games.Select(game =>
        {
            // Natural key: nflverse game_id. Stable across re-syncs, which is
            // what lets this run nightly without duplicating the season.
            var filter = Builders<NflScheduleDocument>.Filter.Eq(g => g.GameId, game.GameId);

            return new UpdateOneModel<NflScheduleDocument>(filter, BuildUpdate(game))
            {
                IsUpsert = true
            };
        }).ToList();

        await _collection.BulkWriteAsync(
            writes, new BulkWriteOptions { IsOrdered = false }, ct);
    }

    /// <summary>
    /// The per-field update for one game.
    ///
    /// <para>
    /// Internal rather than inline so <c>NflScheduleUpdateCoverageTests</c> can
    /// render it and assert its key set against the document's own properties.
    /// An explicit <c>$set</c> list says nothing about what it omits, and a field
    /// added to the document but forgotten here is written once on insert and
    /// never updated again — the failure this codebase keeps rediscovering
    /// (FAN-159 ModelValue, FAN-166 RawValue, FAN-175 IsScored).
    /// </para>
    /// </summary>
    internal static UpdateDefinition<NflScheduleDocument> BuildUpdate(NflScheduleDocument game) =>
        Builders<NflScheduleDocument>.Update
            .Set(g => g.Season, game.Season)
            .Set(g => g.Week, game.Week)
            .Set(g => g.GameType, game.GameType)
            .Set(g => g.Gameday, game.Gameday)
            .Set(g => g.GametimeEt, game.GametimeEt)
            .Set(g => g.Weekday, game.Weekday)
            .Set(g => g.HomeTeam, game.HomeTeam)
            .Set(g => g.AwayTeam, game.AwayTeam)
            .Set(g => g.HomeScore, game.HomeScore)
            .Set(g => g.AwayScore, game.AwayScore)
            .Set(g => g.SpreadLine, game.SpreadLine)
            .Set(g => g.TotalLine, game.TotalLine)
            .Set(g => g.Location, game.Location)
            .Set(g => g.SyncedAt, game.SyncedAt);
    // GameId is the filter key and Id is generated by StringObjectIdGenerator on
    // insert; both are asserted separately in the coverage test.

    public async Task<IReadOnlyList<NflScheduleDocument>> GetByWeekAsync(
        int season, int week, CancellationToken ct = default)
    {
        var filter = Builders<NflScheduleDocument>.Filter.And(
            Builders<NflScheduleDocument>.Filter.Eq(g => g.Season, season),
            Builders<NflScheduleDocument>.Filter.Eq(g => g.Week, week));

        return await _collection.Find(filter)
            .SortBy(g => g.Gameday)
            .ThenBy(g => g.GametimeEt)
            .ToListAsync(ct);
    }

    public async Task<IReadOnlyList<NflScheduleDocument>> GetBySeasonAsync(
        int season, CancellationToken ct = default)
    {
        return await _collection
            .Find(Builders<NflScheduleDocument>.Filter.Eq(g => g.Season, season))
            .SortBy(g => g.Week)
            .ThenBy(g => g.Gameday)
            .ThenBy(g => g.GametimeEt)
            .ToListAsync(ct);
    }

    public async Task<NflScheduleDocument?> GetTeamGameAsync(
        string team, int season, int week, CancellationToken ct = default)
    {
        // Normalised here so callers can pass whatever their own source gave
        // them — Sleeper's LAR, nflverse's LA, a game log's STL.
        var canonical = NflTeamNormalizer.Normalize(team);
        if (canonical.Length == 0) return null;

        var filter = Builders<NflScheduleDocument>.Filter.And(
            Builders<NflScheduleDocument>.Filter.Eq(g => g.Season, season),
            Builders<NflScheduleDocument>.Filter.Eq(g => g.Week, week),
            Builders<NflScheduleDocument>.Filter.Or(
                Builders<NflScheduleDocument>.Filter.Eq(g => g.HomeTeam, canonical),
                Builders<NflScheduleDocument>.Filter.Eq(g => g.AwayTeam, canonical)));

        return await _collection.Find(filter).FirstOrDefaultAsync(ct);
    }

    public async Task<long> CountBySeasonAsync(int season, CancellationToken ct = default) =>
        await _collection.CountDocumentsAsync(
            Builders<NflScheduleDocument>.Filter.Eq(g => g.Season, season), cancellationToken: ct);

    public async Task<int?> GetCurrentWeekAsync(
        int season, DateTime asOfUtc, CancellationToken ct = default)
    {
        var seasonFilter = Builders<NflScheduleDocument>.Filter.Eq(g => g.Season, season);
        var today = asOfUtc.Date;

        // Earliest game of the season. Absent = no schedule imported, which is
        // reported as null so the caller can fall back deliberately rather than
        // reading a 0 as "preseason".
        var opener = await _collection.Find(seasonFilter)
            .SortBy(g => g.Gameday)
            .Limit(1)
            .FirstOrDefaultAsync(ct);

        if (opener is null) return null;
        if (today < opener.Gameday.Date) return 0;

        // The week that owns the next game still to be played. Date-based on
        // purpose: defining the current week by which games are FINAL would make
        // week detection depend on the score sync having run, so a lagging sync
        // would pin the whole site to a week that had already finished.
        //
        // Mid-week this returns the in-progress week, because that week's later
        // games are still ahead. Between a Monday night game and the following
        // Thursday it returns the next week, which is the fantasy convention.
        var next = await _collection.Find(
                Builders<NflScheduleDocument>.Filter.And(
                    seasonFilter,
                    Builders<NflScheduleDocument>.Filter.Gte(g => g.Gameday, today)))
            .SortBy(g => g.Gameday)
            .Limit(1)
            .FirstOrDefaultAsync(ct);

        if (next is not null) return next.Week;

        // Every game is behind us — the season is over. Hold on the final week
        // rather than rolling into a week that does not exist.
        var last = await _collection.Find(seasonFilter)
            .SortByDescending(g => g.Week)
            .Limit(1)
            .FirstOrDefaultAsync(ct);

        return last?.Week ?? 0;
    }
}
