<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Google.OrTools" Version="9.9.3963" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FF.SharedKernel\FF.SharedKernel.csproj" />
    <ProjectReference Include="..\FF.Domain\FF.Domain.csproj" />
  </ItemGroup>
</Project>
