using System.Reflection;
using FF.Domain.Documents;
using FF.Infrastructure.Persistence.Mongo.Repositories;
using FluentAssertions;
using MongoDB.Bson;
using MongoDB.Bson.Serialization;
using Xunit;

namespace FF.Tests.Persistence;

/// <summary>
/// FAN-178, following the pattern established by
/// <see cref="DynastyValuationUpdateCoverageTests"/>.
///
/// <para>
/// <c>nfl_schedule</c> is upserted on a natural key and re-synced daily, which
/// makes an omitted field worse here than elsewhere: the value is written once on
/// the insert and then never updated again, so a game's score or closing line
/// would freeze at whatever it was the first time the season was imported and
/// nothing would ever report it. A schedule that is right in September and stale
/// in December is harder to notice than one that is simply absent.
/// </para>
/// </summary>
public class NflScheduleUpdateCoverageTests
{
    /// <summary>
    /// Properties deliberately outside the <c>$set</c> block, each for a stated
    /// reason. Anything not listed here must be set, and adding to this list
    /// should take an argument rather than a moment.
    /// </summary>
    private static readonly HashSet<string> IntentionallyNotSet = new(StringComparer.Ordinal)
    {
        // The upsert filter key. Setting the field matched on is a no-op at best,
        // and on an insert Mongo supplies it from the filter.
        nameof(NflScheduleDocument.GameId),

        // Generated by StringObjectIdGenerator on insert. Setting it explicitly
        // would write _id: "" and collide the second game in the batch with the
        // first.
        nameof(NflScheduleDocument.Id),
    };

    private static NflScheduleDocument SampleGame() => new()
    {
        GameId = "2026_01_DAL_NYG",
        Season = 2026,
        Week = 1,
        GameType = "REG",
        Gameday = new DateTime(2026, 9, 13, 0, 0, 0, DateTimeKind.Utc),
        GametimeEt = "20:20",
        Weekday = "Sunday",
        HomeTeam = "NYG",
        AwayTeam = "DAL",
        HomeScore = 17,
        AwayScore = 24,
        SpreadLine = -3m,
        TotalLine = 48.5m,
        Location = "Home",
        SyncedAt = DateTime.UtcNow
    };

    private static BsonDocument RenderUpdate(NflScheduleDocument game)
    {
        var serializer = BsonSerializer.SerializerRegistry.GetSerializer<NflScheduleDocument>();
        return NflScheduleRepository
            .BuildUpdate(game)
            .Render(serializer, BsonSerializer.SerializerRegistry)
            .AsBsonDocument;
    }

    [Fact]
    public void BuildUpdate_Sets_EveryDocumentProperty_ExceptThoseExplicitlyExcluded()
    {
        var rendered = RenderUpdate(SampleGame());
        var setKeys = rendered["$set"].AsBsonDocument.Names.ToHashSet(StringComparer.Ordinal);

        var documentProperties = typeof(NflScheduleDocument)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanWrite)          // IsFinal() is a method and never appears here
            .Select(p => p.Name)
            .ToList();

        var missing = documentProperties
            .Where(name => !IntentionallyNotSet.Contains(name) && !setKeys.Contains(name))
            .ToList();

        missing.Should().BeEmpty(
            "every field on NflScheduleDocument must be written on re-sync — an omitted " +
            "one is set on the initial insert and then frozen forever, so a score or " +
            "closing line would silently never update. Add it to BuildUpdate, or to " +
            "IntentionallyNotSet with a reason.");
    }

    [Fact]
    public void BuildUpdate_DoesNotSet_TheFilterKey()
    {
        var rendered = RenderUpdate(SampleGame());
        var setKeys = rendered["$set"].AsBsonDocument.Names.ToHashSet(StringComparer.Ordinal);

        setKeys.Should().NotContain(nameof(NflScheduleDocument.GameId));
        setKeys.Should().NotContain(nameof(NflScheduleDocument.Id));
    }

    /// <summary>
    /// Scores and lines are null until posted. They must still be written, or a
    /// game that had a line and later lost one would keep the stale value — and
    /// more importantly, the null-to-value transition is the whole point of the
    /// daily re-sync.
    /// </summary>
    [Fact]
    public void BuildUpdate_Writes_NullableFields_EvenWhenNull()
    {
        var unplayed = SampleGame();
        unplayed.HomeScore = null;
        unplayed.AwayScore = null;
        unplayed.SpreadLine = null;
        unplayed.TotalLine = null;

        var set = RenderUpdate(unplayed)["$set"].AsBsonDocument;

        set.Contains(nameof(NflScheduleDocument.HomeScore)).Should().BeTrue();
        set.Contains(nameof(NflScheduleDocument.AwayScore)).Should().BeTrue();
        set.Contains(nameof(NflScheduleDocument.SpreadLine)).Should().BeTrue();
        set.Contains(nameof(NflScheduleDocument.TotalLine)).Should().BeTrue();

        set[nameof(NflScheduleDocument.HomeScore)].IsBsonNull.Should().BeTrue();
        set[nameof(NflScheduleDocument.SpreadLine)].IsBsonNull.Should().BeTrue();
    }

    // Deliberately NOT asserted here: that SpreadLine and TotalLine serialise as
    // Decimal128 rather than the driver's default string (FAN-127/129).
    //
    // That behaviour is real and it IS wired up — AddInfrastructure calls
    // MongoSerializationConfig.Register() before RegisterBsonClassMaps(), with a
    // comment forbidding the reverse order — but it is process-global startup
    // configuration, not something BuildUpdate decides. Asserting it from a unit
    // test means either running the app's registration inside the test process,
    // where whichever test serialises a decimal first wins and the result depends
    // on test ordering, or asserting against a locally constructed serializer,
    // which tests nothing about production. An earlier version of this file did
    // the former and failed for exactly that reason.
    //
    // If this needs covering, it belongs in a startup/integration test that owns
    // the process, not beside the coverage assertions.

    [Fact]
    public void IsFinal_IsTrue_OnlyWhenBothScoresArePresent()
    {
        var game = SampleGame();
        game.IsFinal().Should().BeTrue();

        game.AwayScore = null;
        game.IsFinal().Should().BeFalse("a half-populated score is not a final result");

        game.HomeScore = null;
        game.IsFinal().Should().BeFalse();
    }
}
